version: "3.8"
services:
  crud-api-aluno:
    image: postgres
    container_name: crud-api-web2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crud-api-web2
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: